# Generated by Django 5.0.2 on 2024-03-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_images',
            name='ingredient_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
