# Generated by Django 5.0.2 on 2024-03-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_gen', '0005_alter_ingredients_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe_id',
        ),
    ]
